name: Run Tests

on:
  workflow_dispatch:

# Node.js test workflow
jobs:
  filter: 
    runs-on: ubuntu-24.04
    outputs: 
      services: ${{steps.filter.outputs.changes}} # will output a string of json

    steps: 
      - name: checkout code 
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: path changes filter
        id: filter
        uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        with: 
          filters: .github/utils/file-filters.yaml
          token: $${{ secrets.GITHUB_TOKEN }}
          base: HEAD~1 # compare the latest commit compared to the head - 1 


  test-node:
    runs-on: ubuntu-24.04
    needs: filter # so it needs to use the output of the filters
    strategy:
      fail-fast: false
      matrix:
        services: ${{ fromJson(needs.filter.outputs.services) }}

    steps: 
      - name: checkout code 
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      
      # Setup node and react
      - name: Setup Node.js environment
        if: ${{startsWith(matrix.services, 'services/node') || startsWith(matrix.services, 'services/react')}} # Use * because it only cares about the node
        uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6 # v4.4.0
        with: 
          node-version-file: ${{matrix.services}}/package.json # Specify the version to use
          cache: "npm"
          cache-dependency-path: ${{matrix.services}}/package-lock.json

      # Setup go 
      - name: Setup Go-lang environment
        if: ${{startsWith(matrix.services, 'services/go')}}
      
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with: 
          go-version-file: ${{matrix.services}}/go.mod
          cache: true
          cache-dependency-path: ${{matrix.services}}/go.sum

      # install poetry
      - name: install poetry
        if: ${{ startsWith(matrix.services, 'services/python')}}
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 #v1.4.2

      # Setup python
      - name: Setup python environment
        if: ${{ startsWith(matrix.services, 'services/python')}}

        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with: 
          python-version-file: ${{matrix.services}}/pyproject.toml
          cache: poetry
          cache-dependency-path: ${{matrix.services}}/poetry.lock

      # Installing tasksfile for running the test file
      - name: Install task 
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 #v4.0.1
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.53.1/task_linux_amd64.tar.gz"
          name: task
          version: v3.53.1
      
      # Install node dep
      - name: Install app dependencies
        working-directory: ${{matrix.services}}
        run: |
          echo "Starting dependency installation..."
          ls -la
          task install-ci
          
      # Run Test
      - name: Running app test
        working-directory: ${{matrix.services}}
        run: |
          echo "Starting testing test cases..."
          task test